<?php

namespace App\Http\Controllers;

use App\Models\CampaignRecipient;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

/**
 * Open and click tracking endpoints.
 *
 * Both routes are protected by the "signed" middleware (see routes/web.php), so only
 * URLs generated by AutoMail work: recipient ids cannot be enumerated and the click
 * endpoint cannot be abused as an open redirect.
 */
class TrackingController extends Controller
{
    /**
     * Record an email open and return a 1x1 transparent GIF.
     */
    public function trackOpen(int $recipientId): Response
    {
        CampaignRecipient::where('id', $recipientId)
            ->whereNull('opened_at')
            ->update(['opened_at' => now()]);

        $gif = base64_decode('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7');

        return response($gif, 200, [
            'Content-Type' => 'image/gif',
            'Content-Length' => (string) strlen($gif),
            'Cache-Control' => 'no-store, no-cache, must-revalidate, max-age=0',
            'Pragma' => 'no-cache',
        ]);
    }

    /**
     * Record a link click, then redirect to the original destination.
     */
    public function trackClick(Request $request, int $recipientId): RedirectResponse
    {
        $url = (string) $request->query('url', '');

        if (!$this->isSafeUrl($url)) {
            abort(404);
        }

        CampaignRecipient::where('id', $recipientId)
            ->whereNull('clicked_at')
            ->update(['clicked_at' => now()]);

        // A click implies the email was opened (images may be blocked by the mail client).
        CampaignRecipient::where('id', $recipientId)
            ->whereNull('opened_at')
            ->update(['opened_at' => now()]);

        return redirect()->away($url);
    }

    /**
     * Only absolute http(s) URLs are allowed as redirect targets.
     */
    protected function isSafeUrl(string $url): bool
    {
        if ($url === '' || filter_var($url, FILTER_VALIDATE_URL) === false) {
            return false;
        }

        $scheme = strtolower((string) parse_url($url, PHP_URL_SCHEME));

        return in_array($scheme, ['http', 'https'], true);
    }
}
